[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "npm"]

[build.nixpacksPlan.phases.install]
cmds=["npm install --legacy-peer-deps"]

[build.nixpacksPlan.phases.build]
cmds=["npm run build"]

[deploy]
startCommand = "cd .medusa/server && npm install && npm run predeploy && npm run start"
